# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  mandrill_username: Your_Username
  mandrill_apikey: Your_API_Key
  secret_key_base: 5a986df8b70737f7457aa5334140e2991c139e1011d95ff45d1530e3562594036d74ac1d397445eb8400aaf8cfd26cfbde902e2ef81aba928860abe89051109b

test:
  secret_key_base: d34201d8a0869937d3986c8b591b9ec63aba9a2d0e87e376bf199d21b31fd1fca19c5b237cdba84e9e120bd709a0085a550cf6480a80f4828707cfaf00def615

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  mandrill_username: <%= ENV["MANDRILL_USERNAME"] %>
  mandrill_apikey: <%= ENV["MANDRILL_APIKEY"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
